name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  OWNER_LC: ${{ github.repository_owner.lower() }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME }}/client:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME }}/client:latest
          build-args: |
            VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }}
            VITE_CLIENT_ID_OATH=${{ secrets.VITE_CLIENT_ID_OATH }}
            VITE_REDIRECT_URI_OAUTH=${{ secrets.VITE_REDIRECT_URI_OAUTH }}
            VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}
            VITE_OAUTH_URL=${{ secrets.VITE_OAUTH_URL }}
            VITE_SERVER_API_URL=${{ secrets.VITE_SERVER_API_URL }}
            VITE_AVATAR_URL=${{ secrets.VITE_AVATAR_URL }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME }}/server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME }}/server:latest
